// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWxbMYol43bc8PvaR0oo7y_r8wz1aSlR4',
    appId: '1:630791373016:web:2721dc70fd078fd3e5d7ad',
    messagingSenderId: '630791373016',
    projectId: 'tailor-todo-2f31c',
    authDomain: 'tailor-todo-2f31c.firebaseapp.com',
    storageBucket: 'tailor-todo-2f31c.firebasestorage.app',
    measurementId: 'G-2VPB0JBMW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7d_7OcsvfqnSecpCw6TkBhkerTOr2L60',
    appId: '1:630791373016:android:8eb08d37e2bc96aae5d7ad',
    messagingSenderId: '630791373016',
    projectId: 'tailor-todo-2f31c',
    storageBucket: 'tailor-todo-2f31c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDilmCHdAjczIPYX0dVJ2CNe5DWsJEUa0U',
    appId: '1:630791373016:ios:742aaee818545677e5d7ad',
    messagingSenderId: '630791373016',
    projectId: 'tailor-todo-2f31c',
    storageBucket: 'tailor-todo-2f31c.firebasestorage.app',
    iosBundleId: 'com.example.tailorTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDilmCHdAjczIPYX0dVJ2CNe5DWsJEUa0U',
    appId: '1:630791373016:ios:742aaee818545677e5d7ad',
    messagingSenderId: '630791373016',
    projectId: 'tailor-todo-2f31c',
    storageBucket: 'tailor-todo-2f31c.firebasestorage.app',
    iosBundleId: 'com.example.tailorTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWxbMYol43bc8PvaR0oo7y_r8wz1aSlR4',
    appId: '1:630791373016:web:3b2fa1dc0d07d20ee5d7ad',
    messagingSenderId: '630791373016',
    projectId: 'tailor-todo-2f31c',
    authDomain: 'tailor-todo-2f31c.firebaseapp.com',
    storageBucket: 'tailor-todo-2f31c.firebasestorage.app',
    measurementId: 'G-7WRVFGM1JT',
  );
}
